#pragma once

#include "Game/GameTransform.hpp"
#include "Engine/Core/Vertex_PCU.hpp"
#include "Engine/Core/XmlUtils.hpp"

#include <vector>

struct AABB3;
struct Vec3;
class DensityCloud;

//-----------------------------------------------------------------------------------------------
class SDF
{
protected:
	GameTransform m_transform;
public:
	bool m_isPointCloud = false;

protected:
	virtual float ComputeLocalSDF(Vec3 const& localPos) const = 0;

	virtual AABB3 ComputeLocalAABB() const = 0;

public:
	virtual ~SDF() = default;
	virtual const char* GetShapeName() const = 0;
	virtual void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts, Rgba8 const& color = Rgba8::OPAQUE_WHITE) const = 0;

	virtual AABB3 GetAffectedAABB() const; // bounding box for voxel sdf

	// Point Cloud is Generated By SDF, but no sdf definition here
	virtual uint8_t GetPointCloudDensity(Vec3 const& worldPos) const; 

	float GetSignedDistance(Vec3 const& worldPos) const;
	GameTransform& GetMutTransform() { return m_transform; }
	GameTransform const& GetTransform() const { return m_transform; }

	// XML Serialization
	virtual void WritePropertiesToXml(XmlElement& element) const = 0;
	virtual void ReadPropertiesFromXml(XmlElement const& element) = 0;
	virtual const char* GetTypeString() const = 0;
};

void DrawSDFDetail(SDF* sdf);

//-----------------------------------------------------------------------------------------------
// https://iquilezles.org/articles/distfunctions/
class SDFSphere : public SDF
{
private:
	float m_radius;

protected:
	float ComputeLocalSDF(Vec3 const& localPos) const override;
	AABB3 ComputeLocalAABB() const override;
	void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts, Rgba8 const& color = Rgba8::OPAQUE_WHITE) const override;

public:
	SDFSphere(float radius = 1.0f) : m_radius(radius) {}
	const char* GetShapeName() const override { return "Sphere"; }

	float GetRadius() const { return m_radius; }
	void SetRadius(float r) { if (r > 0.f) m_radius = r; }

	// XML Serialization
	void WritePropertiesToXml(XmlElement& element) const override;
	void ReadPropertiesFromXml(XmlElement const& element) override;
	const char* GetTypeString() const override { return "Sphere"; }
};

//-----------------------------------------------------------------------------------------------
class SDFBox : public SDF
{
private:
	Vec3 m_halfExtents;
protected:
	float ComputeLocalSDF(Vec3 const& localPos) const override;
	AABB3 ComputeLocalAABB() const override;
	void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts, Rgba8 const& color = Rgba8::OPAQUE_WHITE) const override;

public:
	SDFBox(const Vec3& halfExtents = Vec3(1.f, 1.f, 1.f))
		: m_halfExtents(halfExtents) {}

	const char* GetShapeName() const override { return "Box"; }

	const Vec3& GetHalfExtents() const { return m_halfExtents; }
	void SetHalfExtents(const Vec3& extents) 
	{ 
		if (extents.x > 0.f && extents.y > 0.f && extents.z > 0.f)
		{
			m_halfExtents = extents; 
		}
	}

	// XML Serialization
	void WritePropertiesToXml(XmlElement& element) const override;
	void ReadPropertiesFromXml(XmlElement const& element) override;
	const char* GetTypeString() const override { return "Box"; }
};

//-----------------------------------------------------------------------------------------------
class SDFTorus : public SDF
{
private:
	float m_majorRadius;
	float m_minorRadius;
protected:
	float ComputeLocalSDF(Vec3 const& localPos) const override;
	AABB3 ComputeLocalAABB() const override;
	void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts, Rgba8 const& color = Rgba8::OPAQUE_WHITE) const override;

public:
	SDFTorus(float majorRadius = 2.0f, float minorRadius = 0.5f)
		: m_majorRadius(majorRadius), m_minorRadius(minorRadius) {
	}

	const char* GetShapeName() const override { return "Torus"; }

	float GetMajorRadius() const { return m_majorRadius; }
	float GetMinorRadius() const { return m_minorRadius; }
	void SetMajorRadius(float r) { if (r > 0.f) m_majorRadius = r; }
	void SetMinorRadius(float r) { if (r > 0.f) m_minorRadius = r; }

	// XML Serialization
	void WritePropertiesToXml(XmlElement& element) const override;
	void ReadPropertiesFromXml(XmlElement const& element) override;
	const char* GetTypeString() const override { return "Torus"; }
};

//-----------------------------------------------------------------------------------------------
class SDFCapsule : public SDF
{
private:
	Vec3 m_pointA;
	Vec3 m_pointB;
	float m_radius;
protected:
	float ComputeLocalSDF(Vec3 const& localPos) const override;
	AABB3 ComputeLocalAABB() const override;
	void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts, Rgba8 const& color = Rgba8::OPAQUE_WHITE) const override;

public:
	SDFCapsule(Vec3 const& pointA = Vec3(0.f, 0.f, -1.f), Vec3 const& pointB = Vec3(0.f, 0.f, 1.f), float radius = 0.5f)
		: m_pointA(pointA), m_pointB(pointB), m_radius(radius) {
	}

	const char* GetShapeName() const override { return "Capsule"; }

	// #ToDo Return Point Ref
	Vec3 const& GetPointA() const { return m_pointA; }
	Vec3 const& GetPointB() const { return m_pointB; }
	float GetRadius() const { return m_radius; }
	void SetPointA(Vec3 const& p) { m_pointA = p; }
	void SetPointB(Vec3 const& p) { m_pointB = p; }
	void SetRadius(float r) { if (r > 0.f) m_radius = r; }

	// XML Serialization
	void WritePropertiesToXml(XmlElement& element) const override;
	void ReadPropertiesFromXml(XmlElement const& element) override;
	const char* GetTypeString() const override { return "Capsule"; }
};

//-----------------------------------------------------------------------------------------------
class SDFCutSphere : public SDF
{
private:
	float m_radius;
	float m_cutHeight;

protected:
	float ComputeLocalSDF(Vec3 const& localPos) const override;
	AABB3 ComputeLocalAABB() const override;
	void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts, Rgba8 const& color = Rgba8::OPAQUE_WHITE) const override;

public:
	SDFCutSphere(float radius = 1.0f, float cutHeight = 0.5f)
		: m_radius(radius), m_cutHeight(cutHeight) {
	}

	const char* GetShapeName() const override { return "CutSphere"; }

	float GetRadius() const { return m_radius; }
	float GetCutHeight() const { return m_cutHeight; }
	void SetRadius(float r);
	void SetCutHeight(float h);

	// XML Serialization
	void WritePropertiesToXml(XmlElement& element) const override;
	void ReadPropertiesFromXml(XmlElement const& element) override;
	const char* GetTypeString() const override { return "CutSphere"; }
};

//-----------------------------------------------------------------------------------------------
class SDFCutHollowSphere : public SDF
{
private:
	float m_radius;
	float m_cutHeight;
	float m_thickness;

protected:
	float ComputeLocalSDF(Vec3 const& localPos) const override;
	AABB3 ComputeLocalAABB() const override;
	void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts, Rgba8 const& color = Rgba8::OPAQUE_WHITE) const override;

public:
	SDFCutHollowSphere(float radius = 1.0f, float cutHeight = 0.5f, float thickness = 0.1f)
		: m_radius(radius), m_cutHeight(cutHeight), m_thickness(thickness) {
	}

	const char* GetShapeName() const override { return "CutHollowSphere"; }

	float GetRadius() const { return m_radius; }
	float GetCutHeight() const { return m_cutHeight; }
	float GetThickness() const { return m_thickness; }
	void SetRadius(float r);
	void SetCutHeight(float h);
	void SetThickness(float t);

	// XML Serialization
	void WritePropertiesToXml(XmlElement& element) const override;
	void ReadPropertiesFromXml(XmlElement const& element) override;
	const char* GetTypeString() const override { return "CutHollowSphere"; }
};

//-----------------------------------------------------------------------------------------------
class SDFDensityCloud : public SDF
{
private:
	DensityCloud* m_densityCloud = nullptr;
	std::string m_filePath;

private:
	Vec3 GetFlooredPosition() const; // The Actual Position(Min Corner of the point cloud)

protected:
	float ComputeLocalSDF(Vec3 const& localPos) const override;
	AABB3 ComputeLocalAABB() const override;
	void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts, Rgba8 const& color = Rgba8::OPAQUE_WHITE) const override;

public:
	SDFDensityCloud();
	~SDFDensityCloud();

	const char* GetShapeName() const override { return "DensityCloud"; }

	AABB3 GetAffectedAABB() const override;
	uint8_t GetPointCloudDensity(Vec3 const& worldPos) const override;

	bool LoadFromFile(const std::string& filePath);
	const std::string& GetFilePath() const { return m_filePath; }
	DensityCloud const* GetDensityCloud() const { return m_densityCloud; }

	// XML Serialization
	void WritePropertiesToXml(XmlElement& element) const override;
	void ReadPropertiesFromXml(XmlElement const& element) override;
	const char* GetTypeString() const override { return "DensityCloud"; }
};



//-----------------------------------------------------------------------------------------------
enum class SDFFillMethod
{
	UNIFORM_BLEND,		// use matID1, matID2, blendValue
	Z_AXIS_GRADIENT,	// matID1 is at the bottom, matID2 is at the top, 
						// minZ factor(0.9), maxZ factor(0.95), Smooth step, e.g. grass on the soil
	DISTANCE_GRADIENT,	// matID1 is inside, matID2 is outside, minDist = -2.0f maxDist = -1.0f, Smooth Step
						// e.g. a watermelon 
};

class SDFShape
{
public:
	SDF* m_sdf = nullptr;
	SDFFillMethod m_fillMethod = SDFFillMethod::UNIFORM_BLEND;

	uint8_t m_materialID1 = 0;
	uint8_t m_materialID2 = 0;

	// Uniform Blend Mode
	float m_uniformBlendValue = 0.f;

	// Z Axis Gradient
	float m_gradientMinZFactor = 0.9f;
	float m_gradientMaxZFactor = 0.95f;

	// Distance 
	float m_gradientMinDist = -2.f;
	float m_gradientMaxDist = -1.f;

public:
	void DebugDrawShape() const;
	void AddWorldVerts(std::vector<Vertex_PCU>& worldVerts) const;

public:
	// Editor
	bool m_isSelected = false;

public:
	// #ToDo Use VoxelMesher to Generate a preview mesh, Will Use TerrainStructuredBuffer 
	// Like Mesh Chunk
	void GeneratePreviewMesh();
	void DestroyPreviewMesh();

public:
	//TerrainStructuredBuffer* m_structuredVertexBuffer = nullptr;

public:
	// Please use new SDFShape, do not create it on stack
	//SDFShape() = default;
	SDFShape(SDF* sdf); // SDF Shape will take control the sdf
	~SDFShape();

	//SDFShape(SDFShape const&) = delete;
	//SDFShape& operator=(SDFShape const&) = delete;
	//SDFShape(SDFShape&& other) noexcept;
	//SDFShape& operator=(SDFShape&& other) noexcept;

	void ComputeVoxelData(Vec3 const& worldPos, uint8_t& out_density, uint8_t& out_matID1, uint8_t& out_matID2, uint8_t& out_blendValue) const;

	// XML Serialization
	void WriteToXml(XmlElement& element) const;
	void ReadFromXml(XmlElement const& element);
	static SDFShape* CreateFromXml(XmlElement const& element);

private:
	uint8_t ComputeZGradientBlend(Vec3 const& worldPos) const;
	uint8_t ComputeDistanceGradientBlend(float signedDist) const;
};

//-----------------------------------------------------------------------------------------------


